# permissions for end users to edit tokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-federated-credential-operator
    app.kubernetes.io/managed-by: kustomize
  name: token-editor-role
rules:
- apiGroups:
  - federatedcredential.arthurvardevanyan.com
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - federatedcredential.arthurvardevanyan.com
  resources:
  - tokens/status
  verbs:
  - get
